create database alunos_notas;
use alunos_notas;
select database();
show tables;
create table ALUNO(
NUMMATR VARCHAR(7) NOT NULL,
CODCUR VARCHAR (6),
NOME VARCHAR (45),
NASCIMENTO DATETIME,
BOLSA FLOAT NULL DEFAULT 0,
E_MAIL VARCHAR (25),
CODEMPR VARCHAR(4),
FUNCAO VARCHAR(10),
DATAINICIO DATETIME,
DATAFIM DATETIME,
INDEX ( CODCUR),
INDEX (CODEMPR),
PRIMARY KEY (NUMMATR)
)ENGINE=MyISAM DEFAULT CHARSET=UTF8;



 CREATE TABLE CURRICULO(
 CODCUR VARCHAR (6) NOT NULL,
 CODDISC VARCHAR (6) NOT NULL,
 INDEX (CODDISC),
 INDEX (CODCUR),
 PRIMARY KEY (CODCUR, CODDISC)
 ) ENGINE=MyISAM DEFAULT CHARSET=UTF8;
 
 CREATE TABLE CURSO(
 CODCUR VARCHAR (6) NOT NULL,
 NOME VARCHAR(45),
 PRIMARY KEY (CODCUR)
 ) ENGINE=MyISAM DEFAULT CHARSET=UTF8;

CREATE TABLE disciplina(
CODDISC VARCHAR (6)NOT NULL,
NOME VARCHAR (45),
PRIMARY KEY (CODDISC)
)ENGINE=MyISAM DEFAULT CHARSET=UTF8;

CREATE TABLE NOTA(
CODDISC VARCHAR(6) not null,
NUMMATR VARCHAR (7) NOT NULL,
P1 FLOAT NULL,
P2 FLOAT NULL,
P3 FLOAT NULL,
P4 FLOAT NULL,
P5 FLOAT NULL,
PRIMARY KEY (NUMMATR),
INDEX(NUMMATR),
INDEX (CODDISC)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8;

SELECT * FROM NOTA;

SELECT * FROM CURRICULO;
select *from disciplina;


INSERT INTO CURRICULO (CODCUR,CODDISC) VALUES ( '305', '050141');
INSERT INTO CURRICULO (CODCUR,CODDISC) VALUES ( '305', '050145');
INSERT INTO CURRICULO (CODCUR,CODDISC) VALUES ( '310', '050141');
INSERT INTO CURRICULO (CODCUR,CODDISC) VALUES ( '310', '050145');
